---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  project: default
  source:
    chart: podinfo
    repoURL: ghcr.io/stefanprodan/charts
    targetRevision: 6.4.0
    helm:
      releaseName: podinfo
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-test
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: podinfo
  namespace: ingress-test
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
    # nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: /podinfo
        # path: /podinfo(/|$)(.*)
        backend:
          service:
            name: podinfo
            port:
              number: 9898