apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-rollouts
    repoURL: https://github.com/domenicbove/argocd-test.git
  syncPolicy:
    automated: {}