apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: podinfo
  namespace: argocd
spec:
  destination:
    namespace: podinfo
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: podinfo
    repoURL: https://github.com/domenicbove/argocd-test/tree/main/charts/podinfo
    targetRevision: 6.4.0
    helm:
      releaseName: podinfo
  syncPolicy:
    automated: {}